### ISSUE TITLE
Converter hangs after app redeployment

### ISSUE THREAD

**Issue by ChrisVinall** [tuespetre/TuesPechkin#104]
Hi,

I've seen a few issues like this but they all seem to be marked resolved.

I'm using TuesPechkin with the 32-bit wk deployment, deployed on IIS 7.5 with the VC++ redistributable installed. The app is otherwise 64-bit, I don't remember why I decided to use 32-bit unfortunately. Reasons. It might just have been because I didn't want to also deploy 64-bit VC++ to our production server for fear of unpredictable consequences.

The converter works fine indefinitely, but then after the app is redeployed, requests to it hang. The only way I know of to fix it is to restart the AppPool or kill w3wp.

Gist of how I'm using TuesPechkin is here: https://gist.github.com/ChrisVinall/1e33da76b3b80a654a2c

The app it's in at the moment is low-traffic and I can probably just put a build step in to restart the AppPool, but I'd like the PDF converter code to be reusable. Hoping someone has some ideas on how to resolve this. I don't have a trace or anything at the moment - hoping to resolve this without having to do work :)

**Comment by crush83** [comment]
I'm having this issue as well. I read on the Pechkin board that because the DLL for wkhtmltox is not managed code, it doesn't get released properly when the app is redeployed.

Seems there should be some way to release/dispose of it when the application is killed.

**Comment by tuespetre** [comment]
@ChrisVinall _seems_ to have a proper usage pattern here: https://gist.github.com/ChrisVinall/1e33da76b3b80a654a2c#file-gistfile1-txt-L22

But @crush83, in your example here: https://github.com/tuespetre/TuesPechkin/issues/48#issuecomment-110865483

You are not using a ThreadSafeConverter, and on top of that you are creating a new instance of the converter/toolset each time the function is run rather than storing it in a static place.

See this section of the README: https://github.com/tuespetre/TuesPechkin#or-in-an-iis-hosted-application

And as I stated, it _does_ seem that @ChrisVinall is following that usage scenario so I am not sure what the matter is in that case.

**Comment by crush83** [comment]
@tuespetre I updated my code to use a Singleton instance and the ThreadSafeConverter yesterday, but alas...I was making a really stupid mistake today, and deploying to a different development server than the one I was checking. I really need to get more sleep...

Product is working great after creating my version of a WinAnyCPUEmbeddedDeployment.

I'm not seeing the hang-up now. Thanks for all your hard work! Really excellent job.

**Comment by ChrisVinall** [comment]
Oh I thought I'd been back here already and closed this. Sorry. My problem was that I'm dumb. Originally I was mistakenly not using a RemotingToolset, but when I changed to using it, the problem appeared to persist. But of course it did, because it's the PREVIOUSLY DEPLOYED build of the app that matters. I needed to redeploy, restart the AppPool, use the converter, then redeploy AGAIN and test. After I did that, the problem disappeared.
