### ISSUE TITLE
Simultaneous converts from different threads crash

### ISSUE THREAD

**Issue by alin-prisecaru** [tuespetre/TuesPechkin#52]
First of all, I really like this plugin. I think it's one of the best out there and easy to use.

Let me explain my problem that I encountered:
I have an application that uses TuesPechkin converter through a Web Api.
So the DLL itself is in this web api that has the only purpose of converting html to PDF.

In some scenarios, with big HTML files (aprox 7mb - 600 pages of PDF) we get an error if we have more than 1 threads trying to access a converter:
I have this method:

``` C#
private void CreatePdfDocumentFromHtml(string htmlContent, string filePath)
{
   IPechkin converter = Factory.Create();
   GlobalSettings settings = new GlobalSettings
                {
                    Margins =
                    {
                        Top = 0.8,
                        Bottom = 0.8,
                        Left = 0.6,
                        Right = 0.6,
                        Unit = Unit.Centimeters
                    },
                    ImageDPI = 200,
                    ImageQuality = 400,
                    DPI = 200
                };   
   HtmlToPdfDocument pdfDocument = new HtmlToPdfDocument
                {
                    GlobalSettings = settings,
                    Objects =
                    {
                        new ObjectSettings
                        { 
                            ProduceLocalLinks = true,
                            ProduceForms = true,
                            HtmlText = htmlContent
                        }                    
                    }                
                };

   converter.Begin += converter_Begin;

   //gets stuck in this method while trying to convert on multiple threads
   byte[] pdfDocumentData = converter.Convert(pdfDocument);

   File.WriteAllBytes(filePath, pdfDocumentData);
}
```

Separately in my class, just for testing purposes:

``` C#
void converter_Begin(IPechkin converter, int expectedPhaseCount)
{
     var a = 1;
}
```

I noticed that when I have 2 or more different threads getting here, only the first to begin triggers the Begin event.
I've seen in the source code that there's a LOCK inside there that deals with these scenarios. Problem is that sometimes, when the first thread has finished its work, I think it also deletes the current progress of the converter on the other threads.

So I get the error related to the Garbage collector or something like that:
![error](https://cloud.githubusercontent.com/assets/8037551/5128743/bad31494-70e5-11e4-9aa2-398bfdc6527a.png)

Just so that you know, it works fine when I make only 1 request with a big file (takes about 10 mins)
OR
more requests simultaneously, but with smaller files that finish in about 1-2 minutes per file. 

I've made a temporary solution that kinda transforms that method in a locked method that only allows 1 thread at a time, but that could mean having a queue and the browser or the Host Application throws a "Task canceled" error, because of the time taken for the request I think.

Please tell me if you have any ideeas or fixes. Sorry for the long boring post.

**Comment by limayesn** [comment]
Hi Tuespetre,
     I had reported this issue in #100. Following above thread about creating AppDomains run time, i have spun up new folders where dlls are copied run time and referenced these in IDeployment specificPath. However, if 2 files (1 large and 1 small) are given for conversion simultaneously,  the files queue up and the smaller file completes after the larger one.
Each file is referencing a wkhtmltox.dll from different folders. As you had suggested in #100, i also looked at "http://stackoverflow.com/questions/1202744/dynamically-p-invoking-a-dll" but still not come up with any solution.
Is there any other work around for this?

**Comment by limayesn** [comment]
Hi Tuespetre,
I had reported this issue in #100. If 2 files (1 large and 1 small) are given for conversion simultaneously, the files queue up and the smaller file completes after the larger one. 
Following above thread about creating AppDomains run time, i have spun up new folders where dlls are copied run time and referenced these in IDeployment specificPath. Because of "static IDeployment specificPath", it always references the first folder dll. If each file is referencing a wkhtmltox.dll from different folders, will the smaller file convert first? As you had suggested in #100, i also looked at "http://stackoverflow.com/questions/1202744/dynamically-p-invoking-a-dll" but still could not come up with any solution. 
You have also mentioned this in #57 that "The only thing I see wrong with your example is that you are instantiating a converter every time". However, that's exactly what i intend to do.
Is there any other work around wherein for each print call, a new IDeployment specificPath is set and  we copy dll to that folder and use this dll? So, the threads are separate for each conversion.

**Comment by tuespetre** [comment]
Sorry @limayesn, currently only one converter may successfully exist and run within a process space. As you pointed out, issue #63 will need to be addressed to properly allow multiple wkhtmltox.dll copies to be used, thus allowing multiple conversions to run truly simultaneously.

An explanation of #63: when using the `[DllImport]` attribute, P/Invoke (part of .NET framework) will only resolve the location of the targeted DLL one time. So in order to make this work, new versions of the `PdfAssembly` and `ImageAssembly` classes need to be created that, instead of relying on `[DllImport]`, instead use `GetProcAddress` and a number of other WinAPI calls to properly hook into a specified copy of wkhtmltox.dll.

**Comment by limayesn** [comment]
Thanks for the explanation Tuespetre. I will see how i can do it, very deep stuff indeed :)
